:doctype: book
:toc: left
:toclevels: 3
:sectnums:
:icons: font
:source-highlighter: highlightjs
:idprefix:
:idseparator: -
:sectlinks:
:sectanchors:
:linkcss: false

:short-bonita-version: 7.15
:doc-url: https://documentation.bonitasoft.com/bonita/7.15
:java-version: 11
= connector-openai-text-davinci-003

The project **connector-openai-example** is a Bonita Connector for **Bonita {short-bonita-version}**  **Community** version. It was written in `groovy` language and uses `Retrofit`: https://square.github.io/retrofit/

This connector is an extension of your Bonita project to connect to OpenAI APIs.

The OpenAI playground is a good way to preview the input and output that you can expect when using these APIs (login is required): https://platform.openai.com/playground/p/default-notes-summary?model=text-davinci-003

== Features

* Creates a completion for the provided prompt. See: https://platform.openai.com/docs/api-reference/completions/create
* Takes as input the prompt, the authentication token and the base URL.
* Returns as output a completion text.
* Uses as default parameters: "text-davinci-003" as model and 2048 as max_tokens.

== Getting started

* For the authentication token
1. Create an account at OpenAI: https://platform.openai.com/
2. Create a new API key: https://platform.openai.com/account/api-keys
3. Copy/paste this key as the input token of your connector.

For more details on Bonita Connector please refer to {doc-url}/connector-archetype[documentation]

== Developing
Here's a brief introduction about what you must do in order to start developing
the project further:

Prerequisite:

- Java ( **jdk {java-version}** or higher)
- Maven (optional if you choosed to use https://github.com/takari/maven-wrapper[maven wrapper script] as archetype option)
- A Git client (optional but highly recommended)

=== Building

[source,bash]
----
git clone https://your.github.com/connector-openai-text-davinci-003.git
cd connector-openai-text-davinci-003/
./mwnw package
----

The build should produce a jar archive under the `target/` folder named `connector-openai-text-davinci-003-1.0.0.jar`

For more details about Apache Maven, please refer to the https://maven.apache.org/guides/getting-started/[documentation]

=== Deploying / Publishing


{doc-url}/managing-extension-studio[Install the connector in your Bonita project using the Studio, window = "_blank"].

== Contributing

This is just an example of a custom connector. 
If you'd like to contribute, please fork the repository and use a feature
branch. Pull requests are warmly welcome.

== Links
. Community Blog Post: 
. Repository: https://github.com/thaliacruz-bonita/custom-connector-openai-example
. OpenAI Reference: https://platform.openai.com/docs/api-reference/completions/create
. Issue tracker: https://github.com/thaliacruz-bonita/custom-connector-openai-example/issues
.. In case of sensitive bugs like security vulnerabilities, please contact
    adoption@bonitasoft.com directly instead of using issue tracker. We value your effort
    to improve the security and privacy of this project!
